title = '{username} 在玩MPSMC.cn~ | MPSMCの狂拽酷炫吊炸天帅天下无敌无服能挡哪服不服干哪服的社会1.20.6无敌牛逼fantanstic的生电整合包-Version.7 by littleQ114514 | Minecraft Fabric {mcversion}'
icon16 = 'customwindowtitle/icon16.png'  
icon32 = 'customwindowtitle/icon32.png'